version: "3.3"

services:
  # app:
  #   image: myapp
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://db:5432
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - ./db/data:/data/db